### ISSUE TITLE
Special characters in filename cause exception

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/timeslice-chronometer#11]
Exception "Illegal character in path" for filename: "file:///Users/ivan/Desktop/Aufnahme_2016-06-10 11.32.15.784.mp4"

**Comment by kmindi** [comment]
I think this is closed by a0571962057be0d0213fb5db1e2c6fd42605cfd0

**Comment by ibogicevic** [comment]
Tested and confirmed.
