### ISSUE TITLE
Short review of v0.3

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/timeslice-chronometer#29]
Please have a look at the most current version. Open issues and assign them to milestone v0.3 if they should be fixed today otherwise to v0.4.

**Comment by ibogicevic** [comment]
Sorry, I forgot that #30 is still open.

**Comment by ibogicevic** [comment]
Ok, review can start. #30 is closed now.

**Comment by kmindi** [comment]
I only moved #28 to Mileston v0.3
