### ISSUE TITLE
Video should be output in tool

### ISSUE THREAD

**Issue by kmindi** [ibogicevic/timeslice-chronometer#4]

**Comment by ibogicevic** [comment]
This feature would specialize the timeslice-chronometer from a generic multi-stopwatch-tool to a video evaluating tool. Therefore (if ever included in this tool) it should be realized as an optional plugin or only be shown when enabled in the settings. If someone wants to implement that feature and include it in such a way, feel free to reopen this ticket.

**Comment by ibogicevic** [comment]
The effort does not seem to be too high when using http://docs.oracle.com/javafx/2/media/playercontrol.htm
-> Reopening this ticket :-)
